# Configuration file

# Contains list of URL
URLs:
  - https://www.example.com
  - https://www.cgi.fi/fi
  - https://yle.fi
  - https://www.linkedin.com
  - https://www.google.com
  - https://www.youtube.com
  - https://www.nordea.fi
  - https://www.tori.fi
  - https://www.hs.fi


  
# Contains list of RegEx
RegEx: 
  - <title>(.*?)</title>
  - <h1>(.*?)</h1>

